# Codex https://developers.openai.com/codex/skills
destination: ~/.agents/skills

skills:
  - source: https://github.com/pivoshenko/pivoshenko.ai
    skills: "*"

  - source: https://github.com/anthropics/skills
    skills:
      - doc-coauthoring
      - frontend-design
