export const SKILL_TAGS: Record<string, string[]> = {
  'doc-coauthoring': ['docs'],
  'frontend-design': ['frontend', 'design'],
  pdf: ['docs'],
  pptx: ['docs'],
  'skill-creator': ['meta'],
  'startup-design': ['startup'],
  'startup-competitors': ['startup'],
  'startup-positioning': ['startup'],
  'startup-pitch': ['startup'],
  'web-design-guidelines': ['frontend', 'design'],
  'deploy-to-vercel': ['vercel', 'deploy'],
  'vercel-optimize': ['vercel', 'perf'],
  'vercel-cli': ['vercel', 'deploy'],
  'building-components': ['frontend', 'design'],
  cloudflare: ['cloudflare'],
  'web-perf': ['frontend', 'perf'],
  'rust-best-practices': ['rust'],
  'grill-me': ['mode'],
  'improve-codebase-architecture': ['engineering'],
  caveman: ['mode'],
  fastapi: ['python', 'api'],
  'building-pydantic-ai-agents': ['ai'],
  'logfire-instrumentation': ['python', 'observability'],
  'logfire-query': ['python', 'observability'],
  'logfire-ui': ['python', 'observability'],
  'pydantic-ai-harness': ['python', 'ai'],
  'memory-management': ['productivity'],
  start: ['productivity'],
  'task-management': ['productivity'],
  update: ['productivity'],
  architecture: ['engineering'],
  debug: ['engineering'],
  'deploy-checklist': ['engineering', 'deploy'],
  documentation: ['engineering', 'docs'],
  'incident-response': ['engineering'],
  standup: ['engineering', 'productivity'],
  'system-design': ['engineering'],
  'tech-debt': ['engineering'],
  'testing-strategy': ['engineering'],
}

export const SOURCE_TAGS: Record<string, string[]> = {
  'vercel-labs/next-skills': ['nextjs'],
  'vercel-labs/agent-skills': ['vercel'],
  'vercel/vercel': ['vercel'],
  'vercel/components.build': ['vercel', 'frontend'],
  'cloudflare/skills': ['cloudflare'],
  'ferdinandobons/startup-skill': ['startup'],
  'pydantic/skills': ['python'],
}

export const MCP_TAGS: Record<string, string[]> = {
  github: ['git', 'github'],
  vercel: ['vercel', 'deploy'],
  motherduck: ['data', 'sql'],
  'cloudflare-api': ['cloudflare'],
  'cloudflare-docs': ['cloudflare', 'docs'],
  'cloudflare-observability': ['cloudflare'],
  logfire: ['observability', 'python'],
}
