export const SKILL_TAGS: Record<string, string[]> = {
  'doc-coauthoring': ['docs'],
  'frontend-design': ['frontend', 'design'],
  pdf: ['docs'],
  pptx: ['docs'],
  'skill-creator': ['meta'],
  'startup-design': ['startup'],
  'startup-competitors': ['startup'],
  'startup-positioning': ['startup'],
  'startup-pitch': ['startup'],
  'web-design-guidelines': ['frontend', 'design'],
  'deploy-to-vercel': ['vercel', 'deploy'],
  'vercel-optimize': ['vercel', 'perf'],
  'vercel-cli': ['vercel', 'deploy'],
  'building-components': ['frontend', 'design'],
  cloudflare: ['cloudflare'],
  'web-perf': ['frontend', 'perf'],
  'rust-best-practices': ['rust'],
  'grill-me': ['mode'],
  'improve-codebase-architecture': ['engineering'],
  caveman: ['mode'],
  fastapi: ['python', 'api'],
  'building-pydantic-ai-agents': ['ai'],
  'logfire-instrumentation': ['python', 'observability'],
  'logfire-query': ['python', 'observability'],
  'logfire-ui': ['python', 'observability'],
  'pydantic-ai-harness': ['python', 'ai'],
  supabase: ['supabase'],
  'supabase-postgres-best-practices': ['supabase', 'sql'],
  'motherduck-connect': ['motherduck', 'data'],
  'motherduck-duckdb-sql': ['motherduck', 'sql'],
  'motherduck-explore': ['motherduck', 'data'],
  'motherduck-query': ['motherduck', 'sql'],
  'motherduck-rest-api': ['motherduck', 'api'],
  'motherduck-create-dive': ['motherduck', 'data'],
  'motherduck-create-flight': ['motherduck', 'data'],
  'motherduck-ducklake': ['motherduck', 'data'],
  'motherduck-load-data': ['motherduck', 'data'],
  'motherduck-model-data': ['motherduck', 'data'],
  'motherduck-security-governance': ['motherduck', 'data'],
  'motherduck-share-data': ['motherduck', 'data'],
  'motherduck-build-cfa-app': ['motherduck', 'data'],
  'motherduck-build-dashboard': ['motherduck', 'data'],
  'motherduck-build-data-pipeline': ['motherduck', 'data'],
  'motherduck-migrate-to-motherduck': ['motherduck', 'data'],
  'memory-management': ['productivity'],
  start: ['productivity'],
  'task-management': ['productivity'],
  update: ['productivity'],
  architecture: ['engineering'],
  debug: ['engineering'],
  'deploy-checklist': ['engineering', 'deploy'],
  documentation: ['engineering', 'docs'],
  'incident-response': ['engineering'],
  standup: ['engineering', 'productivity'],
  'system-design': ['engineering'],
  'tech-debt': ['engineering'],
  'testing-strategy': ['engineering'],
}

export const SOURCE_TAGS: Record<string, string[]> = {
  'vercel-labs/next-skills': ['nextjs'],
  'vercel-labs/agent-skills': ['vercel'],
  'vercel/vercel': ['vercel'],
  'vercel/components.build': ['vercel', 'frontend'],
  'cloudflare/skills': ['cloudflare'],
  'ferdinandobons/startup-skill': ['startup'],
  'pydantic/skills': ['python'],
  'supabase/agent-skills': ['supabase'],
  'motherduckdb/agent-skills': ['motherduck'],
}

// Local instructions use frontmatter `tags` as the source of truth; this map
// is for external instruction sources (per-slug overrides).
export const INSTRUCTION_TAGS: Record<string, string[]> = {}

export const MCP_TAGS: Record<string, string[]> = {
  github: ['git', 'github'],
  vercel: ['vercel', 'deploy'],
  motherduck: ['data', 'sql'],
  cloudflare: ['cloudflare'],
  logfire: ['observability', 'python'],
  supabase: ['supabase', 'sql'],
}
