# === cargo/Cargo.toml ===
# Purpose:  Template for rust-cli / rust-lib `Cargo.toml`. Drop into a rust repository as `Cargo.toml`, substituting tokens. Uncomment [[bin]] for CLI crates.
# Tokens:   {{name}} = crate name; {{description}} = repository description; {{license}} = SPDX expression (e.g. `MIT OR Apache-2.0`); {{homepage}}, {{documentation}} = URLs; {{keywords}} = TOML list of keywords (max 5)
# Override: Add to [dependencies], [features], [[bin]], [[example]]. Do not strip canon-owned [lints.*] and [profile.release] blocks.
# === end ===

[package]
name = "{{name}}"
version = "0.0.0"
edition = "2021"
description = "{{description}}"
authors = ["Volodymyr Pivoshenko"]
license = "{{license}}"
readme = "README.md"
homepage = "{{homepage}}"
repository = "https://github.com/pivoshenko/{{name}}"
documentation = "{{documentation}}"
keywords = {{keywords}}

# [[bin]]
# name = "{{name}}"
# path = "src/main.rs"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "warn"
todo = "warn"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = "symbols"
